name: Code Quality
on:
  push:
    branches:
      - main
      - develop
  pull_request:

jobs:
  sonarcloud:
    name: SonarCloud
    needs: tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Download results
        uses: actions/download-artifact@v3
        with:
          name: results
          path: results

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
